name: jeremylyon
favicon: null
layout_spectrum: 0.24354045395739377
typography_spectrum: 0.6097787998151034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.15995914349332452
  lightness: 0.3137115528807044
  saturation: 0.7856784381438047
  rhythmicContrast: 0.3502769803162664
purpose: []
