name: jeremylyon
favicon: null
layout_spectrum: 0.96199
typography_spectrum: 0.24368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8b7bc'
    - '#51443a'
    - '#241f1c'
    - '#587193'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
