name: jeremylyon
favicon: null
layout_spectrum: 0.24354045395739377
typography_spectrum: 0.6097787998151034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8b7bc'
    - '#51443a'
    - '#241f1c'
    - '#587193'
  brandStrength: 0.25
  lightness: 0.3137115528807044
  saturation: 0.7856784381438047
  rhythmicContrast: 0.3502769803162664
purpose: []
