name: jeremylyon
favicon: null
layout_spectrum: 0.46411
typography_spectrum: 0.36561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8b7bc'
    - '#51443a'
    - '#241f1c'
    - '#587193'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
